version = "1"
name = "Add your macro name here."
description = "Add your macro description here."

# Leave these as-is
analysis_command = "python3 /app/main.py"
category = "language"
visibility = "public"

[analyzer]
  command = "python3 /app/main.py"

[build]
  image = "python:3.10.2-slim-buster"
  steps = "cp -R . /app"
